spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/ryanbook
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

  profiles:
    active: local
    include: oauth

  logging:
    level: debug

  redis:
    host: localhost
    password:
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

